### ISSUE TITLE
I am having error loading the files 

### ISSUE THREAD

**Issue by ank-man** [SamiLhll/macrosyntR#6] opened 2024-07-30 03:06 UTC
rlang::last_trace()
<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `Loci = (Start + End)/2`.
Caused by error in `Start + End`:
! non-numeric argument to binary operator
---
Backtrace:
     ▆
  1. ├─macrosyntR::load_orthologs(...)
  2. │ └─... %>% select(ID, Chr, Start, End, Index)
  3. ├─dplyr::select(., ID, Chr, Start, End, Index)
  4. ├─dplyr::ungroup(.)
  5. ├─dplyr::mutate(., Index = dplyr::row_number())
  6. ├─dplyr::arrange(., Loci)
  7. ├─dplyr::group_by(., Chr)
  8. ├─dplyr::mutate(., Loci = (Start + End)/2)
  9. └─dplyr:::mutate.data.frame(., Loci = (Start + End)/2)
 10.   └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 11.     ├─base::withCallingHandlers(...)
 12.     └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 13.       └─mask$eval_all_mutate(quo)
 14.         └─dplyr (local) eval()

**Comment by SamiLhll** [comment] 2024-07-30 12:17
Hi there, 

I suspect that there's an issue with the formatting of your input files.
In order to help you with this, could you send me the folllowing details : 
- How many species are you trying to load ?
- a sample of all the files that you try to load (e.g. the result of head in bash of head() in R after you load them using read.csv())

Cheers,
Sami

**Comment by SamiLhll** [comment] 2024-09-26 08:49
I'm closing this issue as I can't reproduce your error. Well, I can do it by loading not properly formatted files but this is not an issue from the code. Please refer to the vignette for the correct usage of the package

**Closed as completed** 2024-09-26 08:50 UTC
